// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: bizdemo/bizdemo.proto

package bizdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	common "proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 请求参数
}

func (x *DemoReq) Reset() {
	*x = DemoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizdemo_bizdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoReq) ProtoMessage() {}

func (x *DemoReq) ProtoReflect() protoreflect.Message {
	mi := &file_bizdemo_bizdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoReq.ProtoReflect.Descriptor instead.
func (*DemoReq) Descriptor() ([]byte, []int) {
	return file_bizdemo_bizdemo_proto_rawDescGZIP(), []int{0}
}

func (x *DemoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DemoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 返回参数值
	Data   *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DemoResp) Reset() {
	*x = DemoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bizdemo_bizdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoResp) ProtoMessage() {}

func (x *DemoResp) ProtoReflect() protoreflect.Message {
	mi := &file_bizdemo_bizdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoResp.ProtoReflect.Descriptor instead.
func (*DemoResp) Descriptor() ([]byte, []int) {
	return file_bizdemo_bizdemo_proto_rawDescGZIP(), []int{1}
}

func (x *DemoResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DemoResp) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_bizdemo_bizdemo_proto protoreflect.FileDescriptor

var file_bizdemo_bizdemo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x69, 0x7a, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x69, 0x7a, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x69, 0x7a, 0x64, 0x65, 0x6d, 0x6f,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x19, 0x0a, 0x07, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x44,
	0x65, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x68, 0x0a, 0x07, 0x42, 0x69, 0x7a,
	0x44, 0x65, 0x6d, 0x6f, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x10, 0x2e, 0x62, 0x69, 0x7a, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x62, 0x69, 0x7a, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6d, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x7a,
	0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bizdemo_bizdemo_proto_rawDescOnce sync.Once
	file_bizdemo_bizdemo_proto_rawDescData = file_bizdemo_bizdemo_proto_rawDesc
)

func file_bizdemo_bizdemo_proto_rawDescGZIP() []byte {
	file_bizdemo_bizdemo_proto_rawDescOnce.Do(func() {
		file_bizdemo_bizdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_bizdemo_bizdemo_proto_rawDescData)
	})
	return file_bizdemo_bizdemo_proto_rawDescData
}

var file_bizdemo_bizdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bizdemo_bizdemo_proto_goTypes = []interface{}{
	(*DemoReq)(nil),         // 0: bizdemo.DemoReq
	(*DemoResp)(nil),        // 1: bizdemo.DemoResp
	(*anypb.Any)(nil),       // 2: google.protobuf.Any
	(*common.TestReq)(nil),  // 3: common.TestReq
	(*common.TestResp)(nil), // 4: common.TestResp
}
var file_bizdemo_bizdemo_proto_depIdxs = []int32{
	2, // 0: bizdemo.DemoResp.data:type_name -> google.protobuf.Any
	0, // 1: bizdemo.BizDemo.GetData:input_type -> bizdemo.DemoReq
	3, // 2: bizdemo.BizDemo.Test:input_type -> common.TestReq
	1, // 3: bizdemo.BizDemo.GetData:output_type -> bizdemo.DemoResp
	4, // 4: bizdemo.BizDemo.Test:output_type -> common.TestResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bizdemo_bizdemo_proto_init() }
func file_bizdemo_bizdemo_proto_init() {
	if File_bizdemo_bizdemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bizdemo_bizdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bizdemo_bizdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bizdemo_bizdemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bizdemo_bizdemo_proto_goTypes,
		DependencyIndexes: file_bizdemo_bizdemo_proto_depIdxs,
		MessageInfos:      file_bizdemo_bizdemo_proto_msgTypes,
	}.Build()
	File_bizdemo_bizdemo_proto = out.File
	file_bizdemo_bizdemo_proto_rawDesc = nil
	file_bizdemo_bizdemo_proto_goTypes = nil
	file_bizdemo_bizdemo_proto_depIdxs = nil
}
